# Generated by Django 6.0 on 2026-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pcategory', models.CharField(max_length=30)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='Default.jpg', upload_to='uploads')),
            ],
        ),
    ]
